### 소상공인상권정보 데이터로 국내에 있는 음식점 현황 및 트렌드를 파악해봅시다.

[데이터 링크] https://www.data.go.kr/data/15083033/fileData.do

1. 한식 / 일식 / 중식 음식점 비율 찾기


2. 각 지역별 음식점 비율 계산해보기


3. 한식 음식점들이 많이 사용하는 단어 찾아보기

In [1]:
# 텍스트 분석에 필요한 라이브러리 설치하기
!pip install pecab wordcloud

Collecting pecab
  Using cached pecab-1.0.8.tar.gz (26.4 MB)
  Preparing metadata (setup.py) ... done
Collecting wordcloud
  Using cached wordcloud-1.9.2.tar.gz (222 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /Users/emphimachine/anaconda3/envs/fastcampus/lib/python3.8/site-packages (from pecab) (1.23.5)
Requirement already satisfied: pyarrow in /Users/emphimachine/anaconda3/envs/fastcampus/lib/python3.8/site-packages (from pecab) (12.0.1)
Requirement already satisfied: regex in /Users/emphimachine/anaconda3/envs/fastcampus/lib/python3.8/site-packages (from pecab) (2022.7.9)
Collecting emoji==1.2.0
  Using cached emoji-1.2.0-py3-none-any.whl (131 kB)
Requirement already satisfied: pytest in /Users/emphimachine/anaconda3/envs/fastcampus/lib/python3.8/site-packages (from pecab) (7.1.2)
Requirement already satisfied: pillow in /Users/emphimachine/anaconda3/envs/fastcampus/lib/python3.8/site-packages (from wordcloud) (9.4.0)
Requirement already satisfied: matplotlib in /Users/emphimachine/anaconda3/envs/fastcampus/lib/python3.8/site-packages (from wordcloud) (3.7.0)
Requirement already satisfied: fonttools>=4.22.0 in /Users/emphimachine/anaconda3/envs/fastcampus/lib/python3.8/site-packages (from matplotlib->wordcloud) (4.25.0)
Requirement already satisfied: contourpy>=1.0.1 in /Users/emphimachine/anaconda3/envs/fastcampus/lib/python3.8/site-packages (from matplotlib->wordcloud) (1.0.5)
Requirement already satisfied: python-dateutil>=2.7 in /Users/emphimachine/anaconda3/envs/fastcampus/lib/python3.8/site-packages (from matplotlib->wordcloud) (2.8.2)
Requirement already satisfied: importlib-resources>=3.2.0 in /Users/emphimachine/anaconda3/envs/fastcampus/lib/python3.8/site-packages (from matplotlib->wordcloud) (5.2.0)
Requirement already satisfied: packaging>=20.0 in /Users/emphimachine/anaconda3/envs/fastcampus/lib/python3.8/site-packages (from matplotlib->wordcloud) (22.0)
Requirement already satisfied: pyparsing>=2.3.1 in /Users/emphimachine/anaconda3/envs/fastcampus/lib/python3.8/site-packages (from matplotlib->wordcloud) (3.0.9)
Requirement already satisfied: kiwisolver>=1.0.1 in /Users/emphimachine/anaconda3/envs/fastcampus/lib/python3.8/site-packages (from matplotlib->wordcloud) (1.4.4)
Requirement already satisfied: cycler>=0.10 in /Users/emphimachine/anaconda3/envs/fastcampus/lib/python3.8/site-packages (from matplotlib->wordcloud) (0.11.0)
Requirement already satisfied: attrs>=19.2.0 in /Users/emphimachine/anaconda3/envs/fastcampus/lib/python3.8/site-packages (from pytest->pecab) (22.1.0)
Requirement already satisfied: iniconfig in /Users/emphimachine/anaconda3/envs/fastcampus/lib/python3.8/site-packages (from pytest->pecab) (1.1.1)
Requirement already satisfied: pluggy<2.0,>=0.12 in /Users/emphimachine/anaconda3/envs/fastcampus/lib/python3.8/site-packages (from pytest->pecab) (1.0.0)
Requirement already satisfied: py>=1.8.2 in /Users/emphimachine/anaconda3/envs/fastcampus/lib/python3.8/site-packages (from pytest->pecab) (1.11.0)
Requirement already satisfied: tomli>=1.0.0 in /Users/emphimachine/anaconda3/envs/fastcampus/lib/python3.8/site-packages (from pytest->pecab) (2.0.1)
Requirement already satisfied: zipp>=3.1.0 in /Users/emphimachine/anaconda3/envs/fastcampus/lib/python3.8/site-packages (from importlib-resources>=3.2.0->matplotlib->wordcloud) (3.11.0)
Requirement already satisfied: six>=1.5 in /Users/emphimachine/anaconda3/envs/fastcampus/lib/python3.8/site-packages (from python-dateutil>=2.7->matplotlib->wordcloud) (1.16.0)
Building wheels for collected packages: pecab, wordcloud
  Building wheel for pecab (setup.py) ... done
  Created wheel for pecab: filename=pecab-1.0.8-py3-none-any.whl size=26646665 sha256=64ba3061a1d93b5a60ebf76c92e23c7db265fa73dbc0acfbafe447d9565e9b92
  Stored in directory: /Users/emphimachine/Library/Caches/pip/wheels/16/5f/78/df847c8c75665934ea02b56c17fba3c239c208e76a9956e67b
  Building wheel for wordcloud (setup.py) ... done
  Created wheel for wordcloud: filename=wordcloud-1.9.2-cp38-cp38-macosx_11_0_arm64.whl size=155103 sha256=7c8e1a3856d917045db83f42927fd3244ac6e32d6feeda0fb394bd7329a82911
  Stored in directory: /Users/emphimachine/Library/Caches/pip/wheels/ba/b0/6c/2132245188580a48553d7564b2a9f874c3110fcc17720e2d48
Successfully built pecab wordcloud
Installing collected packages: emoji, pecab, wordcloud
Successfully installed emoji-1.2.0 pecab-1.0.8 wordcloud-1.9.2

In [29]:
# 필요한 라이브러리를 불러옵니다.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from glob import glob
from tqdm.auto import tqdm  # progress bar

In [30]:
# 데이터들을 불러와봅시다.
# 함수의 파라미터로 파일 이름 규칙을 주면, 규칙에 해당하는 파일 이름을 모두 가져오는 함수.
file_list = sorted(glob('./data/상가(상권)정보_20230630/*.csv'))

data = pd.DataFrame()

for file in tqdm(file_list):
# for idx, file in enumerate(file_list):
#     print("Loading %d%%" % (idx/len(file_list)*100))
    temp = pd.read_csv(file, encoding='utf-8')
    data = pd.concat([data, temp], axis=0)
    
data

  0%|          | 0/17 [00:00<?, ?it/s]

/var/folders/yv/w8ztbhkn6494b3sc2x4zzm0c0000gn/T/ipykernel_71271/3979451944.py:10: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(file, encoding='utf-8')
/var/folders/yv/w8ztbhkn6494b3sc2x4zzm0c0000gn/T/ipykernel_71271/3979451944.py:10: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(file, encoding='utf-8')
/var/folders/yv/w8ztbhkn6494b3sc2x4zzm0c0000gn/T/ipykernel_71271/3979451944.py:10: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(file, encoding='utf-8')
/var/folders/yv/w8ztbhkn6494b3sc2x4zzm0c0000gn/T/ipykernel_71271/3979451944.py:10: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(file, encoding='utf-8')
/var/folders/yv/w8ztbhkn6494b3sc2x4zzm0c0000gn/T/ipykernel_71271/3979451944.py:10: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(file, encoding='utf-8')
/var/folders/yv/w8ztbhkn6494b3sc2x4zzm0c0000gn/T/ipykernel_71271/3979451944.py:10: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(file, encoding='utf-8')
/var/folders/yv/w8ztbhkn6494b3sc2x4zzm0c0000gn/T/ipykernel_71271/3979451944.py:10: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(file, encoding='utf-8')
/var/folders/yv/w8ztbhkn6494b3sc2x4zzm0c0000gn/T/ipykernel_71271/3979451944.py:10: DtypeWarning: Columns (2,35) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(file, encoding='utf-8')
/var/folders/yv/w8ztbhkn6494b3sc2x4zzm0c0000gn/T/ipykernel_71271/3979451944.py:10: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(file, encoding='utf-8')
/var/folders/yv/w8ztbhkn6494b3sc2x4zzm0c0000gn/T/ipykernel_71271/3979451944.py:10: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(file, encoding='utf-8')
/var/folders/yv/w8ztbhkn6494b3sc2x4zzm0c0000gn/T/ipykernel_71271/3979451944.py:10: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(file, encoding='utf-8')
/var/folders/yv/w8ztbhkn6494b3sc2x4zzm0c0000gn/T/ipykernel_71271/3979451944.py:10: DtypeWarning: Columns (2,35) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(file, encoding='utf-8')
/var/folders/yv/w8ztbhkn6494b3sc2x4zzm0c0000gn/T/ipykernel_71271/3979451944.py:10: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(file, encoding='utf-8')
/var/folders/yv/w8ztbhkn6494b3sc2x4zzm0c0000gn/T/ipykernel_71271/3979451944.py:10: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(file, encoding='utf-8')
/var/folders/yv/w8ztbhkn6494b3sc2x4zzm0c0000gn/T/ipykernel_71271/3979451944.py:10: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(file, encoding='utf-8')
/var/folders/yv/w8ztbhkn6494b3sc2x4zzm0c0000gn/T/ipykernel_71271/3979451944.py:10: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(file, encoding='utf-8')

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,MA0101202210A0084547,금강산노래광장,NaN,I2,음식,I211,주점,I21101,일반 유흥 주점,I56211,...,4217010300007470000000086,파크장,강원특별자치도 동해시 송정로 11,240806,25789,NaN,지,NaN,129.127525,37.495265
1,MA010120220805430826,에이치속눈썹수강아카데미,NaN,S2,수리·개인,S207,이용·미용,S20702,피부 관리실,S96113,...,4211039021110620001000001,NaN,강원특별자치도 춘천시 동내면 외솔길19번길 80-36,200883,24401,NaN,NaN,NaN,127.758764,37.857831
2,MA010120220805430903,엔젤,NaN,I2,음식,I201,한식,I20101,백반/한정식,I55109,...,4277032022103660000008290,NaN,강원특별자치도 정선군 남면 민둥산로 175-13,233837,26148,NaN,NaN,NaN,128.792089,37.259788
3,MA010120220805430941,누베헤어,NaN,S2,수리·개인,S207,이용·미용,S20701,미용실,S96112,...,4211012500100440010000008,춘천파크자이,강원특별자치도 춘천시 스포츠타운길 458,200200,24472,NaN,3,NaN,127.707653,37.867744
4,MA010120220805430946,공차,NaN,I2,음식,I212,비알코올,I21201,카페,I56229,...,4213033023113500001000001,NaN,강원특별자치도 원주시 지정면 신지정로 211,220821,26354,NaN,NaN,NaN,127.872713,37.374189
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81718,MA0101202303A0020503,꽃개,NaN,G2,소매,G220,애완동물·용품 소매,G22001,애완동물/애완용품 소매업,G47852,...,4377033021106020004000001,NaN,충청북도 음성군 맹동면 덕금로 236,369811,27733,NaN,NaN,NaN,127.546988,36.925111
81719,MA0101202303A0014518,만두를빚다,NaN,I2,음식,I210,기타 간이,I21007,김밥/만두/분식,I56111,...,4311110300100960017052823,NaN,충청북도 청주시 상당구 중앙로 28-1,360012,28543,NaN,1,NaN,127.488871,36.639523
81720,MA0101202303A0107065,골목식당,NaN,I2,음식,I201,한식,I20101,백반/한정식,I56111,...,4375025024104780038023581,NaN,충청북도 진천군 진천읍 중앙서로 10-1,365807,27831,NaN,NaN,NaN,127.442060,36.859096
81721,MA0101202303A0033503,씨유옥천청산점,NaN,G2,소매,G204,종합 소매,G20405,편의점,G47122,...,4373035021100850007007997,NaN,충청북도 옥천군 청산면 지전1길 3,373874,29013,NaN,2,NaN,127.792482,36.344138
81722,MA0101202303A0033505,카페지아니,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,...,4374525028101720000006486,NaN,충청북도 증평군 증평읍 문화로 62,368904,27933,NaN,NaN,NaN,127.590042,36.784990

In [17]:
# 사용할 column을 찾기 위해 데이터의 일부를 사용.
#df = data[:10000]
df = data.sample(n=10000, random_state=42)
df

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
101226,MA010120220812461834,라이풀,NaN,I2,음식,I204,서양식,I20401,경양식,I56123,...,4889045023107000030044442,NaN,경상남도 합천군 대병면 회양관광단지길 28-10,678922,50216,NaN,NaN,NaN,128.018896,35.525334
41200,MA010120220811988835,토리비어,NaN,I2,음식,I211,주점,I21104,요리 주점,I56219,...,2914012800110730006000001,NaN,광주광역시 서구 풍암2로57번길 15-1,502833,62068,NaN,1,NaN,126.883459,35.123442
146236,MA010120220811504078,삼삼공,NaN,I2,음식,I201,한식,I20101,백반/한정식,I56111,...,4117110100105330028010604,서희아리채,경기도 안양시 만안구 문예로52번길 19,430824,14035,NaN,1,NaN,126.934270,37.385396
105044,MA0101202209A0074319,힐링아로마,NaN,G2,소매,G215,의약·화장품 소매,G21503,화장품 소매업,G47813,...,2729010800112130000000403,NaN,대구광역시 달서구 달구벌대로251길 9,704940,42612,NaN,3,NaN,128.504499,35.852968
24645,MA010120220806106502,삼한직업소개소,NaN,N1,시설관리·임대,N104,고용 알선,N10401,고용 알선업,N75110,...,4413111300100470000018661,성현마트,충청남도 천안시 동남구 우영1길 32,330931,31152,NaN,1,NaN,127.140816,36.806736
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33418,MA010120220807938109,신호남부분정비공업사,NaN,S2,수리·개인,S203,자동차 수리·세차,S20301,자동차 정비소,S95212,...,4613013500100520003020674,NaN,전라남도 여수시 시청로 98-1,555800,59635,NaN,NaN,NaN,127.663390,34.770315
435394,MA010120220805087513,케이와이씨파트너스,NaN,M1,과학·기술,M107,본사·경영 컨설팅,M10703,경영 컨설팅업,M71531,...,1153010200108300001000001,디지털탑프라자,서울특별시 구로구 디지털로26길 98,152879,8393,NaN,NaN,NaN,126.897334,37.481578
52418,MA010120220809697390,한신포차,NaN,I2,음식,I211,주점,I21104,요리 주점,I56193,...,4413111600100710020030467,금강빌딩,충청남도 천안시 동남구 수곡1길 10,330938,31176,NaN,1,NaN,127.127007,36.789162
221968,MA010120220813496790,메가존에듀플러스,NaN,P1,교육,P107,교육 지원,P10701,교육컨설팅업,P85701,...,4127110300112580007022565,사동주택,경기도 안산시 상록구 이화6길 4-3,426822,15583,NaN,NaN,NaN,126.854871,37.300170
39987,MA010120220810843129,등나무횟집,NaN,I2,음식,I201,한식,I20111,횟집,I56114,...,4874025321102760004016053,NaN,경상남도 창녕군 남지읍 낙동로 536,635903,50357,NaN,NaN,NaN,128.483050,35.389665

In [20]:
df.iloc[:, 1:11] # 상권업종중분류명
df.iloc[:, 11:15] # 시도명 # 상호명

        시도코드    시도명  시군구코드     시군구명
101226    48   경상남도  48890      합천군
41200     29  광주광역시  29140       서구
146236    41    경기도  41171  안양시 만안구
105044    27  대구광역시  27290      달서구
24645     44   충청남도  44131  천안시 동남구
...      ...    ...    ...      ...
33418     46   전라남도  46130      여수시
435394    11  서울특별시  11530      구로구
52418     44   충청남도  44131  천안시 동남구
221968    41    경기도  41271  안산시 상록구
39987     48   경상남도  48740      창녕군

[10000 rows x 4 columns]

In [31]:
data = data[["상호명", "상권업종대분류명", "상권업종중분류명", "시도명"]]
data

                상호명 상권업종대분류명    상권업종중분류명      시도명
0           금강산노래광장       음식          주점  강원특별자치도
1      에이치속눈썹수강아카데미    수리·개인       이용·미용  강원특별자치도
2                엔젤       음식          한식  강원특별자치도
3              누베헤어    수리·개인       이용·미용  강원특별자치도
4                공차       음식       비알코올   강원특별자치도
...             ...      ...         ...      ...
81718            꽃개       소매  애완동물·용품 소매     충청북도
81719         만두를빚다       음식       기타 간이     충청북도
81720          골목식당       음식          한식     충청북도
81721       씨유옥천청산점       소매       종합 소매     충청북도
81722         카페지아니       음식       비알코올      충청북도

[2417759 rows x 4 columns]

In [32]:
import gc     # garbage collector : 필요없는 메모리를 다시 가져옴. (메모리 청소)
gc.collect()

9587

### 1. 한식 / 일식 / 중식 음식점 비율 찾기

In [39]:
한식 = data.loc[data["상권업종중분류명"] == "한식"]
일식 = data.loc[data["상권업종중분류명"] == "일식"]
중식 = data.loc[data["상권업종중분류명"] == "중식"]
음식점 = data.loc[data["상권업종대분류명"] == "음식"]

print("한식 비율 : %.2f%%" % (len(한식) / len(음식점) * 100))
print("일식 비율 : %.2f%%" % (len(일식) / len(음식점) * 100))
print("중식 비율 : %.2f%%" % (len(중식) / len(음식점) * 100))

한식 비율 : 40.84%
일식 비율 : 2.63%
중식 비율 : 3.75%

### 2. 각 지역별 음식점(한식) 비율 계산해보기

In [37]:
# 대분류명 "음식"을 기준으로 각 지역별 데이터 개수에서 "음식" 데이터 개수를 나누면 계산 가능.
시도명 = data["시도명"].unique()
for 시도 in 시도명:
    sido = data.loc[data["시도명"] == 시도]
    sido_hansik = sido.loc[sido["상권업종중분류명"] == "한식"]
    print(f"{시도} 한식 비율: {(len(sido_hansik)/len(sido)*100):.2f}%")

강원특별자치도 한식 비율: 18.13%
경기도 한식 비율: 12.02%
경상남도 한식 비율: 16.86%
경상북도 한식 비율: 17.25%
광주광역시 한식 비율: 11.45%
대구광역시 한식 비율: 13.23%
대전광역시 한식 비율: 13.12%
부산광역시 한식 비율: 13.77%
서울특별시 한식 비율: 9.66%
세종특별자치시 한식 비율: 13.82%
울산광역시 한식 비율: 15.91%
인천광역시 한식 비율: 13.12%
전라남도 한식 비율: 16.07%
전라북도 한식 비율: 13.76%
제주특별자치도 한식 비율: 14.78%
충청남도 한식 비율: 16.08%
충청북도 한식 비율: 16.42%

### 3. 한식 음식점들이 많이 사용하는 단어 찾아보기